name: Deployment xsiam-lab

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  infra_deployment:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-24.04
    name: Terraform Deployment
    env:
      working-directory: ./infra
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BACKEND: ${{ vars.S3_BACKEND }}
      AUTHCODES: ${{ vars.AUTHCODES }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Write authcodes to tfvars
          working-directory: ${{ env.working-directory }}
          run: |
            cat >> terraform.tfvars <<EOF
            authcodes = "${{ env.AUTHCODES }}"
            EOF
      - name: Terraform Deployment
        id: init
        working-directory: ${{ env.working-directory }}
        run: |
          terraform init \
          -backend-config="bucket=${{ env.S3_BACKEND }}" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="key=terraform.tfstate"

          terraform plan -var-file=terraform.tfvars -input=false 