name: Deployment xsiam-lab

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
    CORTEX_API_KEY: ${{secrets.CORTEX_API_KEY}}
    CORTEX_API_KEY_ID: ${{secrets.CORTEX_API_KEY_ID}}
    CORTEX_API_URL: https://api-davila.xdr.us.paloaltonetworks.com

jobs:
  cortex_code_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Download cortexcli
      run: |
        set -x
        crtx_resp=$(curl "${CORTEX_API_URL}/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
          -H "x-xdr-auth-id: ${CORTEX_API_KEY_ID}" \
          -H "Authorization: ${CORTEX_API_KEY}")
        crtx_url=$(echo $crtx_resp | jq -r ".signed_url")
        curl -o cortexcli $crtx_url
        chmod +x cortexcli
        ./cortexcli --version

    - name: Run Cortex CLI Code Scan
      run: |
        ./cortexcli \
          --api-base-url "${CORTEX_API_URL}" \
          --api-key "${CORTEX_API_KEY}" \
          --api-key-id "${CORTEX_API_KEY_ID}" \
          code scan \
          --directory "${{github.workspace}}" \
          --repo-id "${{github.repository}}" \
          --branch "${{github.ref_name}}" \
          --source "GITHUB_ACTIONS" \
          --create-repo-if-missing

  infra_deployment:
    needs: cortex_code_scan
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-24.04
    name: Terraform Deployment
    env:
      working-directory: ./infra
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BACKEND: ${{ vars.S3_BACKEND }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Write variables to tfvars
        working-directory: ${{ env.working-directory }}
        run: |
          echo "" >> terraform.tfvars
          cat >> terraform.tfvars <<EOF
          authcodes = "${{ vars.AUTHCODES }}"
          region = "${{ env.AWS_REGION }}"
          name_prefix = "${{ vars.DEPLOYMENT_NAME }}"
          ssh_key_name = "${{ vars.SSH_KEY_NAME }}"
          global_tags = ${{ vars.GLOBAL_TAGS }}
          mgt_public_ips = ${{ vars.MGT_PUBLIC_IP }}
          EOF
      - name: Terraform Deployment
        id: init
        working-directory: ${{ env.working-directory }}
        run: |
          terraform init \
          -backend-config="bucket=${{ env.S3_BACKEND }}" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="key=terraform.tfstate"

          terraform apply -auto-approve -var-file=terraform.tfvars -input=false 